// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repository.go -destination=internal/repository/mocks/mock_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Albert-Ti/go-diploma-tpl/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BalanceWithdrawalsTx mocks base method.
func (m *MockRepository) BalanceWithdrawalsTx(ctx context.Context, order string, sum float64, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BalanceWithdrawalsTx", ctx, order, sum, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// BalanceWithdrawalsTx indicates an expected call of BalanceWithdrawalsTx.
func (mr *MockRepositoryMockRecorder) BalanceWithdrawalsTx(ctx, order, sum, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BalanceWithdrawalsTx", reflect.TypeOf((*MockRepository)(nil).BalanceWithdrawalsTx), ctx, order, sum, userID)
}

// CreateOrder mocks base method.
func (m *MockRepository) CreateOrder(ctx context.Context, order string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockRepositoryMockRecorder) CreateOrder(ctx, order, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockRepository)(nil).CreateOrder), ctx, order, userID)
}

// GetBalance mocks base method.
func (m *MockRepository) GetBalance(ctx context.Context, userID int) (models.BalanceResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(models.BalanceResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockRepositoryMockRecorder) GetBalance(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockRepository)(nil).GetBalance), ctx, userID)
}

// GetOrderUserID mocks base method.
func (m *MockRepository) GetOrderUserID(ctx context.Context, order string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderUserID", ctx, order)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderUserID indicates an expected call of GetOrderUserID.
func (mr *MockRepositoryMockRecorder) GetOrderUserID(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderUserID", reflect.TypeOf((*MockRepository)(nil).GetOrderUserID), ctx, order)
}

// GetOrders mocks base method.
func (m *MockRepository) GetOrders(ctx context.Context, userID int) ([]models.OrdersResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, userID)
	ret0, _ := ret[0].([]models.OrdersResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockRepositoryMockRecorder) GetOrders(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockRepository)(nil).GetOrders), ctx, userID)
}

// GetUser mocks base method.
func (m *MockRepository) GetUser(ctx context.Context, login string) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, login)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUser indicates an expected call of GetUser.
func (mr *MockRepositoryMockRecorder) GetUser(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockRepository)(nil).GetUser), ctx, login)
}

// GetWithdrawals mocks base method.
func (m *MockRepository) GetWithdrawals(ctx context.Context, userID int) ([]models.WithdrawalsResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]models.WithdrawalsResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockRepositoryMockRecorder) GetWithdrawals(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockRepository)(nil).GetWithdrawals), ctx, userID)
}

// ProcessedOrderTx mocks base method.
func (m *MockRepository) ProcessedOrderTx(ctx context.Context, order string, status models.OrderStatus, accrual float64, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessedOrderTx", ctx, order, status, accrual, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessedOrderTx indicates an expected call of ProcessedOrderTx.
func (mr *MockRepositoryMockRecorder) ProcessedOrderTx(ctx, order, status, accrual, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessedOrderTx", reflect.TypeOf((*MockRepository)(nil).ProcessedOrderTx), ctx, order, status, accrual, userID)
}

// RegisterTx mocks base method.
func (m *MockRepository) RegisterTx(ctx context.Context, login, pass string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTx", ctx, login, pass)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterTx indicates an expected call of RegisterTx.
func (mr *MockRepositoryMockRecorder) RegisterTx(ctx, login, pass any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTx", reflect.TypeOf((*MockRepository)(nil).RegisterTx), ctx, login, pass)
}

// UpdateStatusOrder mocks base method.
func (m *MockRepository) UpdateStatusOrder(ctx context.Context, order string, status models.OrderStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusOrder", ctx, order, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusOrder indicates an expected call of UpdateStatusOrder.
func (mr *MockRepositoryMockRecorder) UpdateStatusOrder(ctx, order, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusOrder", reflect.TypeOf((*MockRepository)(nil).UpdateStatusOrder), ctx, order, status)
}
