CREATE TABLE orders (
  id BIGSERIAL PRIMARY KEY,
  number VARCHAR(255) UNIQUE NOT NULL,
  status INTEGER,
  user_id BIGINT REFERENCES users(id),
  uploaded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);